### PR TITLE
Fixed finishing early if a nested template finishes

### LINKED ISSUE #17: Support nested templates in stacks
When using a stack with multiple nested templates the monitoring and logging of events stops when the first `CREATE_COMPLETE` comes in. This means that if using multiple nested templates, only the first one is monitored.

Side note (might open another issue), events are not logged for nested templates...would be awesome to add this functionality as well.

### PR DESCRIPTION
**Pull request by mymattcarroll**
Closes #17

### CODE REVIEW

**Comment by mymattcarroll** [comment]
@andyday, I have tested my change manually by creating/updating/deleting templates both with and without nested templates but Im open to suggestions on how to improve test coverage with in the unit tests.

**Comment by mymattcarroll** [comment]
@andyday, it seems the build is now failing. I can confirm this is not a result of the changes in the Pull Request based on this: https://travis-ci.org/Nordstrom/cfn

**Comment by andyday** [comment]
Looks like the changes here are fairly small.  Formatting changes make it difficult to identify real changes.  I think most (if not all) of this extra noise will go away if you merge in the latest master.  It has similar standardjs formatting changes.  Once you've done this I'll take a look.

**Comment by mymattcarroll** [comment]
Awesome, thanks @andyday. Ill merge now.

Just an FYI, when you are looking at merge requests with lots of white space, you can tick the `Hide whitespace changes` changes under `Diff settings:
image

**Comment by mymattcarroll** [comment]
@andyday, I have rebased with `master`. I just noticed that your `.travis.yml` configuration is still using yarn to run tests, is this intentional?

**Comment by andyday** [comment]
@mymattcarroll no I noticed that as well.  It will still run the npm scripts, but need to change it soon.  As for the whitespace trick, thanks for the tip.

**Comment by andyday** [comment]
published to npm as 1.5.1

**Pull request merged**
