### PR TITLE
Add support for tagging templates

### PR DESCRIPTION
**Pull request by kmcgill88**
Great project to simplify and track CloudFormation deployments! I needed the ability to tag my CF templates resources at the template level so I added it. Thanks for considering merging it back in!

### CODE REVIEW

**Comment by kmcgill88** [comment]
@andyday I've been using this successfully since I posted this PR. Let me know if you'd like to see any changes to get this addition merged. Thanks!

**Comment by marcelboettcher** [comment]
@andyday Would love to see this one merged!
@kmcgill88 Thx for the contribution!

**Comment by andyday** [comment]
Sorry for the delay.   Please resolve conflicts.

**Comment by kmcgill88** [comment]
Awesome! I'll get it cleaned up soon!

**Comment by kmcgill88** [comment]
@andyday something is up with travis. `error Couldn't find the binary (standard | snazzy) && nyc mocha`. Tests pass locally.

**Comment by kmcgill88** [comment]
@andyday let me know if I can do anything to get this in.

**Comment by andyday** [comment]
remove the node 4.3 config in the travis config file.  replace it with node 8

**Comment by kmcgill88** [comment]
Goode to go!

**Comment by andyday** [comment]
Published to npm as 1.5.0

**Pull request merged**
